### ISSUE TITLE
indentation in pages_cache example, request for link to github

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa-doc#7]
The indentation is wrong here: https://pwa.spomky-labs.com/the-service-worker/workbox/warm-caching#page-caching

```yaml

                      - 'app_articles'
                      - 'app_top_articles'
                        params:
                            display: 5
```

Can you add a link from the documentation back to the github page, e.g. "See an error?  Fix it here..."
